# Generated by Django 3.2.7 on 2021-10-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=70)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=30)),
                ('ruc', models.CharField(max_length=15)),
                ('dire', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=20)),
                ('celular1', models.CharField(max_length=15)),
                ('celular2', models.CharField(max_length=15)),
                ('telef1', models.CharField(max_length=15)),
                ('telef2', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('web', models.CharField(max_length=30)),
                ('banco', models.CharField(max_length=30)),
                ('cuenta', models.CharField(max_length=40)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedors',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(choices=[('BJ', 'BALDE'), ('BG', 'BOLSA'), ('BX', 'CAJA'), ('KG', 'KILOGRAMO'), ('LTR', 'LITRO'), ('NIU', 'UNIDAD')], max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('maximo', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.grupo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper', models.CharField(choices=[('VENTA', 'VENTA NACIONAL'), ('COMPRA', 'COMPRA NACIONAL'), ('DEVO', 'DEVOLUCIÓN RECIBIDA'), ('OTROS', 'OTROS')], max_length=50)),
                ('comp', models.CharField(choices=[('Factura', 'Factura'), ('Boleto', 'Boleto de Venta'), ('Guia', 'Guía de remisión')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('serie', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=10)),
                ('cant', models.IntegerField()),
                ('cost', models.FloatField()),
                ('costTotal', models.FloatField()),
                ('scant', models.IntegerField()),
                ('scost', models.FloatField()),
                ('scostTotal', models.FloatField()),
                ('xcant', models.IntegerField()),
                ('xcost', models.FloatField()),
                ('xcostTotal', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.proveedor')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardexs',
            },
        ),
    ]
